import type { Metadata } from "next";
import "./globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css"
import Navbar from "@/components/partials/Navbar";
import Footer from "@/components/partials/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navbar/>
          {children}
          <Footer/>
          </main>
      </body>
    </html>
  );
}
